services:
  bot:
    container_name: MemberPaymentManageBot
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - CasruDB:/app/data
      - ./qrcodes:/app/qrcodes
    env_file:
      - .env
    environment:
      - DISCORD_TOKEN:${DISCORD_TOKEN}
      - CLIENT_ID:${CLIENT_ID}
      - GUILD_ID:${GUILD_ID}
      - PASSWORD:${PASSWORD}
      - ZBARIMG_EXECUTABLE:${ZBARIMG_EXECUTABLE}
      - ADMIN_PASSWORD:${ADMIN_PASSWORD}
    restart: always

volumes:
  CasruDB:
    name: CasruDB
    driver: local
