services:
  bot:
    container_name: MemberPaymentManageBot
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - CasruDB:/app/data
      - ./qrcodes:/app/qrcodes
    env_file:
      - .env
    restart: always

volumes:
  CasruDB:
    name: CasruDB
    driver: local
