services:
  bot:
    container_name: MemberPaymentManageBot
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - MemberPaymentManageBotDB:/app/casru.db
    env_file:
      - .env
    environment:
      - DISCORD_TOKEN = ${DISCORD_TOKEN}
      - CLIENT_ID = ${CLIENT_ID}
      - GUILD_ID = ${GUILD_ID}
      - ALLOWED_USERS = ${ALLOWED_USERS}
    restart: always

volumes:
  MemberPaymentManageBotDB:
    name: MemberPaymentManageBotDB
